version: '3'
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile-db
    image: postgres
    networks:
    - game-logger
  back:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "5000:5000"
    volumes:
    - .:/src
    networks:
    - game-logger
    command: ["./wait-for-it.sh", "postgres:5432", "--", "npm", "run", "dev-back"]
  front:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "5001:5001"
    volumes:
    - .:/src
    networks:
    - game-logger
    command: ["npm", "run", "dev-front"]
networks:
  game-logger: