name: Deploy
on:
  release:
    types: [created]
env:
  PROJECT_NAME: game-logger
  IMAGE_URL: docker.pkg.github.com/${{ github.repository }}/game-logger:${{ github.sha }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          login-server: docker.pkg.github.com
          username: ${{ github.ACTOR }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          cd front
          yarn install --frozen-lockfile --production
          yarn run build
          mv build ../server/front
      - run: |
          cd server
          docker build . -t ${{ env.IMAGE_URL }}
          docker push ${{ env.IMAGE_URL }}
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_CONFIG }}
      - uses: azure/k8s-create-secret@v1
        with:
          namespace: ${{ secrets.K8S_NAMESPACE }}
          secret-type: generic
          arguments: --from-literal=secret=${{ secrets.AUTH_SECRET }}
          secret-name: auth
      - uses: azure/k8s-create-secret@v1
        with:
          namespace: ${{ secrets.K8S_NAMESPACE }}
          secret-type: generic
          arguments: --from-literal=host=${{ secrets.DB_HOST }} --from-literal=name=${{ secrets.DB_NAME }} --from-literal=user=${{ secrets.DB_USER }} --from-literal=pass=${{ secrets.DB_PASS }}
          secret-name: database
      - uses: azure/k8s-create-secret@v1
        with:
          namespace: ${{ secrets.K8S_NAMESPACE }}
          container-registry-url: docker.pkg.github.com
          container-registry-username: essem
          container-registry-password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
          secret-name: regcred
      - run: kubectl delete deployment -n ${{ secrets.K8S_NAMESPACE }} ${{ env.PROJECT_NAME }} || echo "deployment does not exist";
      - run: kubectl delete job -n ${{ secrets.K8S_NAMESPACE }} ${{ env.PROJECT_NAME }}-migrate || echo "job does not exist";
      - uses: azure/k8s-deploy@v1
        with:
          manifests: kubernetes/${{ env.PROJECT_NAME }}-migrate.yml
          namespace: ${{ secrets.K8S_NAMESPACE }}
          images: ${{ env.IMAGE_URL }}
          imagepullsecrets: regcred
      - run: kubectl wait --for=condition=complete --timeout=120s -n ${{ secrets.K8S_NAMESPACE }} job/${{ env.PROJECT_NAME }}-migrate
      - run: sed -i'' 's/<ingress-url>/${{ secrets.DEPLOY_URL }}/g' kubernetes/${{ env.PROJECT_NAME }}.yml
      - uses: azure/k8s-deploy@v1
        with:
          manifests: kubernetes/${{ env.PROJECT_NAME }}.yml
          namespace: ${{ secrets.K8S_NAMESPACE }}
          images: ${{ env.IMAGE_URL }}
          imagepullsecrets: regcred
